### ISSUE TITLE
[Bug] Custom variable effect sometimes doesn't store values

### ISSUE THREAD

**Issue by Concede** [crowbartools/Firebot#1035]
**Describe the bug**
When creating a command/effect list you sometimes come across an issue where firebot does not process the effects correctly.

**To Reproduce**
Unable to reproduce on demand.
See attached .firebotsetup for a "broken" command.

**Expected behavior**
In firebot setup, command should pull "name" from the custom variable json object, but pulls null instead,
if you recreate the command it works fine. I created this command normally (did not "duplicate" etc.)

**Firebot Version:** 5.35.1

**Computer OS:** Windows 10

[Broken command.zip](https://github.com/crowbartools/Firebot/files/6148436/Broken.command.zip)

**Comment by ebiggz** [comment]
Thank you for including a setup of an example thats broken. 

After some debugging I found the issue and fixed it. 
Issue happens when you type something into the "Property path" field of the Custom Variable effect but then clear the field. This would leave the value as an empty string but code later on only does a null check and thus gets confused. This is also why recreating will fix, assuming you dont edit the "property path" field again.
