### ISSUE TITLE
[Bug] No TTS Voice options on Manjaro Linux

### ISSUE THREAD

**Issue by Dolinmyster** [crowbartools/Firebot#1553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I do not have an option to select a TTS Voice in Manjaro Linux. I don't personally want to use the Google TTS, and would like to use one I installed or the system one. I'm not sure if it just doesn't see the installed TTS Voice, or if it's a limitation of Manjaro. Below is what I get when I look at the voices. When I attempt to use TTS, I do not get any sounds. 

https://i.imgur.com/jbyp4od.png

### Version

v5.49.4

### What operating system are you using Firebot on?

Linux Distro

### Contact Details (Optional)

Dolinmyster#6725

**Comment by brumoen** [comment]
Hi, currently TTS on Linux is unsupported due to a limitation in Electron which Firebot is built upon.
There are ways to get around this, but it's not easily implemented in the application due to all the different Linux distributions and their different approaches to the TTS system.

So for Linux I would suggest that you use the Amazon Poly TTS integration that's already in-place.
