### ISSUE TITLE
[Feature Request] simulate events to bypass the one time per x requirement 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1782]
**Describe the solution you'd like**
While simulating any and all events  reusing the username  requires a restart of firebot, If you have a user only event  and you simulate it you must restart firebot to test it again. the reason for this is its respecting the event cooldown 

This should use the same logic as the activity feed where you can spam the event if needed.

so it would be an amazing feature to add  an option to override/bypass cooldowns in event simulators.

**Comment by V1perN3st** [comment]
I would like to see this as well. We should be able to simulate multiple raids (because it came happen) to not only make sure the Effects trigger (which can include conditions and have different effect for different raids) are working, but that everything is working as expected. Yes, the play button allows it to quick similar the effects, but it always uses Firebot Twitch Account and 5 people. If I use conditions for specific streamers and/or raid amounts, than it is harder to test as I have to test it once, restart the program (which wipes my chat history on the program), test the next one, restart the program, etc.... This also makes it hard for testing the queue with multiple raid messages.
