### ISSUE TITLE
[Feature Request] Add time limit for TTS effect

### ISSUE THREAD

**Issue by mgway** [crowbartools/Firebot#1797]
**Describe the solution you'd like**
It would be great if you could limit TTS to the first Y seconds. There's only so many times one can hear TTS from a message full of 7s that results in Microsoft Sam spelling out the number. 

**Additional context**
I'm aware that there is a `Clear Effects` effect, but it would be nice to truncate the sound without intervention.

**Comment by zunderscore** [comment]
The `$textSubstring` variable can accomplish this today. For example: if you have a channel reward that triggers TTS based on the reward message entered by the viewer, instead of using the `$rewardMessage` variable on its own and having TTS read the entire message, you could use `$textSubstring[$rewardMessage, 0, 100]` to only read the first 100 characters.

**Comment by mgway** [comment]
Thanks for the tip. I'll rewrite this issue for adding a time limit only since there is still the possibility of relatively short messages producing unfortunately long TTS results.
