### ISSUE TITLE
[Feature Request] Enhance Announce support to include the variants

### ISSUE THREAD

**Issue by DragynsLair** [crowbartools/Firebot#1837]
Currently /announce is supported

Can we get support for /announceblue, /announcegreen, /announceorange and /announcepurple?

**Comment by zunderscore** [comment]
I'll check the current IRC chat client to see if it supports the color variants now, but last time we checked (couple of months ago), the IRC client only supported the main `/announce` command.

Otherwise, we're dependent on Twurple implementing the new Announcement API endpoint. Once Twurple has support for it, we can consume it, but we probably won't be able to do this until then.

If I get a chance soon, I'll try to submit a PR to Twurple to add the code we need for this.

**Comment by zunderscore** [comment]
Created an issue over on Twurple repo: https://github.com/twurple/twurple/issues/369

And related PR: https://github.com/twurple/twurple/pull/370

Fingers crossed that this can make it into a release soon. Once it is, I'll work on getting support added into Firebot.

**Comment by zunderscore** [comment]
Code has been approved for Twurple. Just waiting on them to roll a release and we'll get Firebot updated to add support.
