### ISSUE TITLE
[Bug] Settings.json 

### ISSUE THREAD

**Issue by vyressi** [crowbartools/Firebot#1863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My client had an issue where firebot 5.53.2 Win64 would not retain settings, and open the onboarding wizard every time software ran, with all of the information pre-populated.  Subsequently, the software would fail frequently and need to be reloaded, to go through that wizard every time.  Software was unusable in this state.

Troubleshooting determined that %appdata%/firebot/profile/%profilename%/settings.json had been replaced with a 1486 byte file containing nothing but binary nulls.  Firebot would complete the wizard and this file would not be overwritten with a proper settings file, so on next program load the software would exhibit this symptom.

The null-filled settings.json was not filesystem read only or had faulty ACL's, but it was stored in backups roughly 30 loads prior..  backup_1660185680268_v5.53.2 did not exhibit the null-filled file
backup_1660186642542_v5.53.2 did

Removing and reloading firebot to generate a new settings.json, or replacing the settings.json with a non-nulled backup restored full functionality.

Client's storage device does not have any filesystem inconsistencies that would be explanatory.  Even if it did, would recommend filebot be adapted to fail more gracefully if settings.json has an invalid header.

### Version

5.53.2

### What operating system are you using Firebot on?

Windows 10

**Comment by SReject** [comment]
This is a known issue that we are slowly mitigating. Firebot is split into to main sets of processes: The window/UI and backend processing.

Currently, settings.json gets corrupted as a result of both processes attempting to update settings.json simultaneously. We are slowly migrating away from having the window/UI process(es) write to file but due to the pervasiveness throughout the project it will take time.
