### ISSUE TITLE
[Feature Request] Make badge and emote URL variables usable with "Viewer Arrived" event

### ISSUE THREAD

**Issue by DontCallMeChicken** [crowbartools/Firebot#2247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`$userBadgeUrls` does not work within an event. Determined with the "Viewer Arrived" effect. After adding the "Show Image/Gif" effect, I couldn't add the variable.
Then I created the effect somewhere else, copied it and tried to add it to the event. It gave me an error message and I couldn't create the effect:

> Replace Variable Error
> Variable: $userBadgeUrls
> Error: $userbadgeurls does not support this specific trigger type: event

### Expected Behavior

`$userBadgeUrls` should work in an event exactly like `$userAvatarUrl`.

### Steps To Reproduce

see above

### Version

v5.58.1

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
no log output
```

### Contact Details (Optional)

Discord: dontcallmechicken.dcmc (old: DCMC#4352)

**Comment by CKY-** [comment]
After looking this is working as intended as the chat message event is the only one that contains the user badge information.
 we will change this to a request to have the raw chat message added to the "Viewer Arrived" Event so that the $userBadgeUrls is useable from within the "Viewer Arrived" Event
