### ISSUE TITLE
[Feature Request] Event Filtering to use Restrictions

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2412]
Can we please update filtering for Events to use the same Restrictions from commands for uniformity 

being able to Restrictions an event for view time or game would be really useful.

**Comment by zunderscore** [comment]
Restrictions and Filters are two distinct concepts in Firebot. Restrictions make sense for things like commands and channel rewards because those are things that a viewer purposefully does in order to perform some action. Restrictions say, "Don't even perform this action unless X condition is met."

Events, on the other hand, are essentially notifications that an action *has already been* performed. It may result from user interaction, but not because they are *going* to do something, but rather because they've already *done* it, so it doesn't make sense to "restrict" it. The event is us deciding what we choose to do with the thing that has already happened. Filters, then, are a way for us to say, "Hey, we only care that this thing just happened if X condition is met."

We're more than happy to add additional event filters. We just need to know what data you would like to filter on. In the meantime, I'll close this issue. Please feel free to create new issues for whatever new event filters you'd like to have added.
