### ISSUE TITLE
[Feature Request] Add Event option when user arrive or leave in chat

### ISSUE THREAD

**Issue by florian-luce** [crowbartools/Firebot#2541]
**Describe the solution you'd like**
I would like to be able to trigger actions when a user arrives or leaves the chat.

**Additional context**
"Viewer Arrived" seems to only work when a user writes in chat
"Viewer Timeout" Does not seem to be related to the chat leaving action

So I would like a "Viewer chat Arrived" which is triggered when a user or bot, present or not in the database, is triggered each time a user arrives in chat
And same behavior with "Viewer chat leaved" when they leave the chat

**Comment by florian-luce** [comment]
I don't know if it's _Twitch IRC_ that is used with FireBot, but 'Join' and 'Part' may be the triggers I'm talking about:
https://dev.twitch.tv/docs/irc/#supported-irc-messages

**Comment by brumoen** [comment]
This hasn't been implemented in Firebot due to the behavior of said feature. Twitch doesn't tell you when a single user joins your chat in real-time, it tells you in 5-15 minute intervals. So we decided not to add this function as it isn't reliable.
If Twitch changes this at any point we might add it, but before Firebot was ported to Twitch, back on Mixer, we refused to add this functionality as it's a bad practice to call out people that are just entering your stream to lurk or check you out before they talk in your chat.
