### ISSUE TITLE
[Feature Request] Ability to stop auto updates

### ISSUE THREAD

**Issue by TheBlackParrot** [crowbartools/Firebot#2769]
**Describe the solution you'd like**
I'd like an option to prevent auto-updates from happening until a time *I, myself* set. Most of the updates end up breaking something vital to my stream and I don't have ample enough time to go back and check/fix things. Pressing ESC at the update prompt only delays it until the next time I start.

**Additional context**
I've ended up just downloading a nupkg file for 5.62.1 and extracting files from that elsewhere, then renaming anything having to do with "squirrel" or "update" to something else just so it doesn't have a chance to force an update. I understand the need to force updates like this, but I'd like to update *on a time that works for me*.

**Comment by CKY-** [comment]
closing as duplicate of #1930

**Comment by TheBlackParrot** [comment]
Defferring updates are not what I'm talking about at all, it's still going to force an update in at most 7 days. I'd prefer updating when I have the time to sit down and make sure everything works, even if that exceeds the 7 day period.

I guess I can continue breaking installations for the time being though, it's not very elegant, but it works. /shrug

**Comment by CKY-** [comment]
what exactly broke in your setup. and why haven't you reported that break during the beta period. what are you referring to that is broken. while i single handedly test all functionality every beta cycle i cant test every use case.

**Comment by itsjesski** [comment]
@TheBlackParrot To jump in on this on behalf of the dev team. We decided a long time ago that we are always going to force updates. We may add additional ways to defer them, but there will always be updates. In return, we try to limit the number of updates we push until we have a significant number of changes that need to be addressed.

**Comment by SwooshyCueb** [comment]
> @TheBlackParrot To jump in on this on behalf of the dev team. We decided a long time ago that we are always going to force updates. We may add additional ways to defer them, but there will always be updates. In return, we try to limit the number of updates we push until we have a significant number of changes that need to be addressed.

What kind of testing infrastructure do you have for handling updates?

**Comment by zunderscore** [comment]
> What kind of testing infrastructure do you have for handling updates?

We're a small, community-driven project with our core staff all being volunteers. We don't have testing infrastructure.

**Comment by SwooshyCueb** [comment]
IMO if you do not have the resources for proper testing infrastructure for handling updates, you should not be forcing updates like this.

**Comment by zunderscore** [comment]
> IMO if you do not have the resources for proper testing infrastructure for handling updates, you should not be forcing updates like this.

Between the small number of volunteers we have, along with dependence on a platform whose API changes somewhat frequently between updates, new features, and deprecations, it isn't feasible for us to support an array of older versions.

Speaking for the dev team, respectfully, this is our decision based on what we're able to support. As @itsjesski noted already, we have made this decision in order to best balance forced updates vs. what we're able to support.

**Comment by BusterNeece** [comment]
Given the most recent update and the impact it's had on users, I think it may be useful to revisit this question with an eye toward improving the end-user experience with major, possibly breaking, releases.

I completely understand that this project is small and doesn't have the people power to facilitate more robust testing before releases. But the fact that releases _don't_ undergo any sort of automated testing is, IMO, another reason why they probably shouldn't be force-pushed out to every user.

I can understand being more assertive about pushing out updates that reflect API changes, security vulnerabilities or other hotfixes, but it's pretty clear from the changelog of the latest version that it made _sweeping_ changes across the codebase, changes that were certainly likely to have unexpected side effects. I'm a little surprised it shipped as a minor release instead of a major one, given the sheer scale of the release.

There is no obligation on the part of your team as maintainers to _support_ these older versions that may be lingering around. It's a simple matter of, if a user is on an older version, they're doing so at their own risk, with no support provided on any channel until they're on the latest version. Yeah, I know How Users Are with this kind of thing, but I think the burden of telling users on outdated software to just update is a much smaller one than the reputational burden of being seen as a constantly-shifting foundation upon which it's not super safe to build a stream.

I don't say this with no experience under my belt; I maintain a widely popular piece of FOSS multimedia software myself. And every release I push has an extensive suite of linting, style checks, type checks and static analysis that runs on both the backend and frontend of the app, holding it to an exactingly high standard. And **even still**, I don't force compulsory updates on my users. In fact, I don't think they'd _tolerate_ me dictating to them a narrow window of time when their infrastructure will go down for an update. They'd stage a mutiny. And my response to users reporting bugs on older versions is simple: update and call me back if it's still happening, because the odds are high it won't be. That's the trade-off with such a large project being depended on by such a small team in my case.

I know this kind of feedback is often received with some serious hostility from other FOSS maintainers, so I apologize if it upsets any maintainers. I promise I mean well, and I only speak up because I've seen first-hand how the current mechanism is causing serious issues for streamers.

**Comment by zunderscore** [comment]
Released in 5.65.2
