### ISSUE TITLE
Start Utilizing A Database

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#543]
Implement the SQL Database. This database will be used for the viewer list. 

- [x] Build easy to use functions for adding, removing, and changing entries.

Notes:
Plan for having multiple profiles. Everything should have unique internal ids.

**Comment by ebiggz** [comment]
For future reference, it seems after some research by Kateract and input from Probable, NeDb might be the solution we go with. 

I see no problem with using it, as long as its fast and works well. It is a nosql database tho, and it will make importing scorp data a little more difficult.

**Comment by ebiggz** [comment]
Also, I'd personally advocate against the second bullet point about moving settings out of JSON and into the database. JSON is perfect for settings files, where we don't expect them to be constantly growing or being appended too (like a user database). Plus leaving it in JSON makes it super easy for us or a savvy user to edit a setting directly with a text app. 

I think settings should stay in JSON. Button, command, and event data could be either in a database or json (since we typically only load them on app load or when cache is refreshed). However things like user data, stats, etc should definitely be in a database.

If I am missing a major negative to keeping settings in JSON tho, I am all ears.

**Comment by kateract** [comment]
I agree with keeping the settings in JSON, having them in a file that can be human readable is good for if they change something and get into an unrecoverable state. They can just pop open the config file and figure out where things went wrong.

As far as scorpbot import, this is something that we can definitely use [sql,js](https://github.com/kripken/sql.js) for, since it's a one time import and we don't have to worry about synchronization as much since they're probably only going to want to do this once.

**Comment by Firebottle** [comment]
This has been implemented. We'll need to go back later to add the stats database, and I'm sure we'll continually work on this as needed. But the basics are in place.
