### ISSUE TITLE
Multi Profile

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#544]
Implement the ability to log into the app with multiple different profiles. When a profile is changed we should swap out all settings for the new profile.

- [x] Build out a folder structure for each logged in profile.
- [x] Controls, commands, events, should be profile specific.
- [x] Update interactive, commands, event and all other caches on profile change.
- [x] A global settings file be created for non profile specific settings.
- [x] UI should allow adding and deleting new profiles.
- [x] A new profile should be created on startup automatically.

**Comment by ebiggz** [comment]
This one will be tricky. Some settings we probably *wont* want  to be user specific. For example the **auto update** setting... since all users shares the same application, letting them both choose what autoupdate type they want wouldn't make sense. 

I also think we should just force the app to restart after a user profile change. I say this from experience after trying to implement a soft reload with the Restore logic. Doing a hard restart is way less bug prone and will make things easier on us. Plus I don't think it will be a big hindrance to the user either.
