### ISSUE TITLE
Local videos don't work since the last update.

### ISSUE THREAD

**Issue by DullieTV** [crowbartools/Firebot#609]
## What version of Firebot are you running?
Version 0.8.18

## Please describe the issue or feature requests in as much detail as possible.
Since I installed version 0.8.18 local videos don't show in OBS and my stream. Local sounds and pictures work fine. Youtube videos are working as well. Only local videos don't show up. Nothing changed from my side. Paths and settings are exactly the same. I tried the troubleshooting but there are still no videos showing in my stream.

(I'm streaming on Mixer)

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Hi @DullieTV 

Are you using regular OBS or Streamlabs OBS? If you are using Streamlabs OBS, mp4 videos will not work as SLOBS doesnt support mp4s in its browsersource.

**Comment by ThePerry-2015** [comment]
Closed since this is an issue with StreamLabs OBS, not Firebot.
We can't do anything about SLOBS not supporting HTML5 in their browser source overlays.
The only thing we can do is suggest that you convert your video files to WebM instead of mp4 as ebiggz suggested or that you switch back to regular OBS if you need support for your mp4 files.
