### ISSUE TITLE
[Feature Request] .mov with alpha channel support

### ISSUE THREAD

**Issue by Esva** [crowbartools/Firebot#626]
Would like to request firebot to have .mov support along with RGB + Alpha Channel so .mov files with alpha channel can be displayed on stream correctly.

**Comment by ThePerry-2015** [comment]
Firebot supports the three formats supported in HTML5, we will not include other video formats in Firebot since we rely on the formats supported by the browser source overlay in the different streaming softwares like OBS, XSplit and SLOBS(This one actually only supports WebM via browser source). These three formats are MP4 , OGG(OGV) and WebM. If you need to use mov-files I suggest that you add these as media sources, setup hotkeys for showing/removing the layer and then use the Game Controls effect in Firebot to turn that source on and off with the same key combination. That is the closest you can get to use mov-files in Firebot.
