### ISSUE TITLE
Feature Request: Save Button for Mixplay Editor

### ISSUE THREAD

**Issue by 0xW1sKy** [crowbartools/Firebot#662]
## What version of Firebot are you running?
5.0.0.0-beta5

## Please describe the issue or feature requests in as much detail as possible.
When editing the Mixplay visuals in Firebot, I can't seem to find a 'save' button after I've made changes. I don't seem to see the changes I've made appear in the mixer lab section either. How do I know the changes I've made have been saved before I start a stream?

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by 0xW1sKy** [comment]
note: an undo button would be nice too. i accidentally deleted an existing button and had to recreate.

**Comment by ebiggz** [comment]
Hi @0xW1sKy , we have no save button because your changes are automatically saved every time you make one. You can even make changes while you are actively connected to your channel and youll see the buttons under your channel move/change live. 

While you can import controls from the devlab, we do not actively sync with with it. So any changes you make in firebot wont be reflected in the devlab, even if you originally imported controls from one. We intentionally cut out the middle man of the devlab for V5 to make creating mixplay experiences quicker and easier.

As for an undo button, we can certainly look into that to help prevent mistakes in the future. Currently tho, deleting a button triggers a secondary confirmation modal, so you actually have to click delete twice before anything is actually deleted. We feel is an adequate mechanism for preventing most accidents for the time being.
