### ISSUE TITLE
Exception list for currency systems

### ISSUE THREAD

**Issue by LastMageTV** [crowbartools/Firebot#664]
We need the ability to exclude certain usernames (like bots) from earning currency.

**Comment by brumoen** [comment]
I'm wondering if we should broaden the exclusion to cover hours, messages and mixplay interactions as well.
So kind of a Freeze function, so you can tag an account to be frozen so they won't earn points/currency or gain hours, messages and MixPlay interactions unless unfrozen.

**Comment by LastMageTV** [comment]
That's a good idea. Can you think of any reason someone would want to free the currency a person gets, but continue letting them get chat messages and everything else? Would a general "freeze stats" checkbox do the trick so that they dont gain anything?

**Comment by brumoen** [comment]
Say it's an account that always lurks in the channel, but rarely interacts, and the main reason for lurking is to have "top" hours so that they can use them to win giveaways/prizes due to an high amount of hours?
Would be nice to be able to freeze the amount of hours and say accumulation of points/currency, but still let them gain chat messages and MixPlay interactions.

**Comment by ebiggz** [comment]
Added "Disable automatic stat accrual" checkbox to the Viewer Details Modal
