### ISSUE TITLE
"Show HTML" effect doesnt display correctly

### ISSUE THREAD

**Issue by Davemane42** [crowbartools/Firebot#672]
## Firebot Version ##
Firebot v5.5.0

## The Issue ##
The "Show HTML" effect only show up when the exit animation is played.
a work around is to "update" the overlay by displaying an image

## HTML code used ##
```
<html>
<head>
<style>
h1 {
  color: black;
  border: 10px solid black;
  margin-top: -10px;
  margin-left: auto;
  margin-right: auto;
  text-align: center;
  max-width: 512px;
  min-width: 512px;
  
  background-color: white;
}
</style>
</head>
<body>

<img src="$userAvatarUrl" width="512" height="512" style = "display: block; margin: auto; border: 10px solid black;">
<h1>Thanks you for the follow <br>$user</h1>

</body>
</html>
```
## Feature Request ##
also, would be nice to have an "Enter animation" like images and such for the HTML effect

**Comment by ebiggz** [comment]
Hi @Davemane42 
Thanks for providing an HTML snippet. I tried it out and it works the first time but indeed stops working after subsequent uses. I think this is largely because the HTML effect isnt really designed to take in an entire HTML document. We can look into ways of mitigating that. In the mean time, altering your HTML to the following makes it work properly every time:
```html
<div>
  <style>
    h1 {
      color: black;
      border: 10px solid black;
      margin-top: -10px;
      margin-left: auto;
      margin-right: auto;
      text-align: center;
      max-width: 512px;
      min-width: 512px;
      background-color: white;
    }
  </style>
  <img src="$userAvatarUrl" width="512" height="512" style = "display: block; margin: auto; border: 10px solid black;">
  <h1>Thanks you for the follow <br>$user</h1>
</div>
```

Also, we could definitely add the enter animations in. We originally left them out to give you more control. To add an enter animation as it stands currently, you just need to add a couple CSS classes to the wrapper div like so:
```html
<div class="animated fadeIn">
  <style>
    h1 {
      color: black;
      border: 10px solid black;
      margin-top: -10px;
      margin-left: auto;
      margin-right: auto;
      text-align: center;
      max-width: 512px;
      min-width: 512px;
      background-color: white;
    }
  </style>
  <img src="$userAvatarUrl" width="512" height="512" style = "display: block; margin: auto; border: 10px solid black;">
  <h1>Thanks you for the follow <br>$user</h1>
</div>
```
You can find a list of animation names [here](https://github.com/daneden/animate.css#animations)
